title: Rafael Dalsenter - Engenheiro de Software
author: Rafael Dalsenter
email: rafaeldalsenter@gmail.com
description: >
  Graduado em Ciência da Computação, desenvolvedor .NET desde 2011. Prefiro Windows Forms que WPF :p
show_excerpts: true

sass:
  sass_dir: _sass
plainwhite:
  name: Rafael Dalsenter
  tagline: Engenheiro de Software
  date_format: "%b %-d, %Y"
  sitemap: true

  social_links:
    github:  rafaeldalsenter
    linkedIn: in/rafael-dalsenter-549931186

theme: plainwhite

plugins:
  - jekyll-seo-tag