title: Rafael Dalsenter - Engenheiro de Software
author: Rafael Dalsenter
email: rafaeldalsenter@gmail.com
description: >
  Graduado em Ciência da Computação e desenvolvedor .NET desde 2012. Gosto de desenvolvimento backend, deploys e devops no geral. A minha idéia é compartilhar os testes e estudos que faço :)
show_excerpts: true

url: http://rafaeldalsenter.github.io
sass:
  sass_dir: _sass
plainwhite:
  name: Rafael Dalsenter
  tagline: Engenheiro de Software
  date_format: "%b %-d, %Y"
  sitemap: true
  disqus_shortname: default
  analytics_id: 'UA-150912686-1'

  social_links:
    github:  rafaeldalsenter
    linkedIn: in/rafael-dalsenter-549931186
    instagram: rafaeldals

theme: plainwhite

plugins:
  - jekyll-seo-tag